fT = gFld("<i>Tuning</i>", "")

GENERAL_INFO = insFld(fT, gFld("General Server Information", ""))
	DATABASE = insFld(GENERAL_INFO, gFld("Database", ""))
		insDoc(DATABASE, gLnk("Database Information", "/orb/jsp/oracle/info/DBInfo.jsp"))

		INIT_PARAM = insFld(DATABASE, gFld("Init Parameters", ""))
			insDoc(INIT_PARAM, gLnk("Parameters", "/orb/jsp/oracle/Generic-sys.jsp?sqlTag=DB_INIT_PARAM"))
			insDoc(INIT_PARAM, gLnk("Non-Default", "/orb/jsp/oracle/Generic-sys.jsp?sqlTag=DB_INIT_NON_DEFAULT_PARAM"))				
			insDoc(INIT_PARAM, gLnk("Description", "/orb/jsp/oracle/Generic-sys.jsp?sqlTag=DB_INIT_PARAM_DESC"))
			insDoc(INIT_PARAM, gLnk("UnDocument", "/orb/jsp/oracle/Generic-sys.jsp?sqlTag=DB_INIT_PARAM_UNDOC"))
			insDoc(INIT_PARAM, gLnk("System Modifiable", "/orb/jsp/oracle/Generic-sys.jsp?sqlTag=DB_INIT_PARAM_ISSES"))
			insDoc(INIT_PARAM, gLnk("Session Modifiable", "/orb/jsp/oracle/Generic-sys.jsp?sqlTag=DB_INIT_PARAM_ISSYS"))

	INSTANCE = insFld(GENERAL_INFO, gFld("Instance", ""))
		insDoc(INSTANCE, gLnk("Background Processes", "/orb/jsp/oracle/info/Background.jsp"))
		insDoc(INSTANCE, gLnk("SGA", "/orb/jsp/oracle/info/SGA.jsp"))
		insDoc(INSTANCE, gLnk("System Statistics", "/orb/jsp/oracle/info/DBInfo.jsp"))

	CONTROL_FILE = insFld(GENERAL_INFO, gFld("Control File", "/orb/jsp/oracle/info/Controlfile.jsp"))
		insDoc(CONTROL_FILE, gLnk("Info", ""))

	LOG = insFld(GENERAL_INFO, gFld("Log", ""))
		insDoc(LOG, gLnk("Redo Logs", "/orb/jsp/oracle/info/Log.jsp"))
		insDoc(LOG, gLnk("Log History", "/orb/jsp/oracle/info/LogHistory.jsp"))
		insDoc(LOG, gLnk("Buffer Allocation Retry", "/orb/jsp/oracle/info/LogBuffAllocation.jsp"))
		insDoc(LOG, gLnk("Archive", "/orb/jsp/oracle/info/Archive.jsp"))

USER_INFO = insFld(fT, gFld("User Information", ""))
	insDoc(USER_INFO, gLnk("Session Info", "/orb/jsp/oracle/user/Session.jsp"))
	insDoc(USER_INFO, gLnk("Session Stat", "/orb/jsp/oracle/user/SessionStat.jsp"))
	insDoc(USER_INFO, gLnk("Open Cursor", "/orb/jsp/oracle/user/OpenCursor.jsp"))
	insDoc(USER_INFO, gLnk("Session Cursor Cache", "/orb/jsp/oracle/user/SessionCursorCache.jsp"))
	insDoc(USER_INFO, gLnk("System Cursor Cache", "/orb/jsp/oracle/user/SystemCursorCache.jsp"))
	insDoc(USER_INFO, gLnk("User SQL", "/orb/jsp/oracle/user/UserSQL.jsp"))
	insDoc(USER_INFO, gLnk("Problem SQL", "/orb/jsp/oracle/user/ProblemSQL.jsp"))
	insDoc(USER_INFO, gLnk("User Lock", "/orb/jsp/oracle/user/UserLock.jsp"))
	insDoc(USER_INFO, gLnk("User Lock Detail", "/orb/jsp/oracle/user/UserLockDetail.jsp"))
	insDoc(USER_INFO, gLnk("User In RBS", "/orb/jsp/oracle/user/UserInRollbackSegs.jsp"))
	insDoc(USER_INFO, gLnk("Lock in RBS", "/orb/jsp/oracle/user/LockInRollbackSegs.jsp"))

CUP = insFld(fT, gFld("CPU", ""))
	REPARSING = insFld(CUP, gFld("Reparsing", ""))
		insDoc(REPARSING, gLnk("Counts", "/orb/jsp/oracle/cpu/Reparse.jsp"))
		insDoc(REPARSING, gLnk("SQL", "/orb/jsp/oracle/cpu/ReparseSQL.jsp"))
		insDoc(REPARSING, gLnk("High Buffer Gets", "/orb/jsp/oracle/cpu/BufferGets.jsp"))
		insDoc(REPARSING, gLnk("Session CPU", "/orb/jsp/oracle/cpu/SessionCPU.jsp"))

	BUFFER_SCAN = insFld(CUP, gFld("Buffer Scan", ""))
		insDoc(BUFFER_SCAN, gLnk("Average", "/orb/jsp/oracle/cpu/BufferScan.jsp"))

	EVENT_WAIT = insFld(CUP, gFld("Event Wait", ""))
		insDoc(EVENT_WAIT, gLnk("Detection", "/orb/jsp/oracle/cpu/Wait.jsp"))
		insDoc(EVENT_WAIT, gLnk("User", "/orb/jsp/oracle/cpu/Wait-User.jsp"))
		insDoc(EVENT_WAIT, gLnk("Background", "/orb/jsp/oracle/cpu/Wait-BG.jsp"))


MEMORY = insFld(fT, gFld("Memory", ""))
		insDoc(MEMORY, gLnk("SGA", "/orb/jsp/oracle/info/SGA.jsp"))
		insDoc(MEMORY, gLnk("SGA Detail", "/orb/jsp/oracle/mem/SGADetail.jsp"))

	DETAIL = insFld(MEMORY, gFld("Detail", ""))
		insDoc(DETAIL, gLnk("Redo Buffer", "/orb/jsp/oracle/mem/Redo.jsp"))

		VARIALBE = insFld(DETAIL, gFld("Variable Size", ""))
			SHARED_POOL = insFld(VARIALBE, gFld("Shared Pool", "/orb/jsp/oracle/mem/SharedPool.jsp"))
				insDoc(SHARED_POOL, gLnk("Dictionary", "/orb/jsp/oracle/mem/Dictionary.jsp"))
				insDoc(SHARED_POOL, gLnk("Library", "/orb/jsp/oracle/mem/Library.jsp"))
				insDoc(SHARED_POOL, gLnk("Reserved", "/orb/jsp/oracle/mem/SharedPoolReserved.jsp"))

			PRIVATE_SQL = insFld(VARIALBE, gFld("Private SQL", ""))
				insDoc(PRIVATE_SQL, gLnk("Reparsing", "/orb/jsp/oracle/mem/Reparsing.jsp"))
				insDoc(PRIVATE_SQL, gLnk("Who", "/orb/jsp/oracle/mem/ReparsingWho.jsp"))

			insDoc(VARIALBE, gLnk("Session Cache Cursor", "/orb/jsp/oracle/mem/Cursor.jsp"))

		insDoc(DETAIL, gLnk("Database Buiffers", "/orb/jsp/oracle/mem/Buffer.jsp"))

IO = insFld(fT, gFld("I/O", ""))
	SPACE_MANAGEMENT = insFld(IO, gFld("Space Management", ""))
		TABLESPACE = insFld(SPACE_MANAGEMENT, gFld("Tablespace", ""))
			insDoc(TABLESPACE, gLnk("Size & Status", "/orb/jsp/oracle/io/TSSize.jsp"))
			insDoc(TABLESPACE, gLnk("Parameters", "/orb/jsp/oracle/io/TSParam.jsp"))
			insDoc(TABLESPACE, gLnk("Free Space", "/orb/jsp/oracle/space/TSFreeSpace.jsp"))

		DATA_FILE = insFld(SPACE_MANAGEMENT, gFld("Data File", ""))
			insDoc(DATA_FILE, gLnk("Size & Status", "/orb/jsp/oracle/io/DBFile.jsp"))
			insDoc(DATA_FILE, gLnk("Free Space", "/orb/jsp/oracle/space/FreeSpace.jsp"))

		EXTENT = insFld(SPACE_MANAGEMENT, gFld("Extent", ""))
			insDoc(EXTENT, gLnk("Extent", "/orb/jsp/oracle/io/Extent.jsp"))
			insDoc(EXTENT, gLnk("Fragmentated?", "/orb/jsp/oracle/io/DynamicExtenstion.jsp"))

		OBJECT = insFld(SPACE_MANAGEMENT, gFld("Object", ""))
			insDoc(OBJECT, gLnk("Size", "/orb/jsp/oracle/space/ObjSize.jsp"))

	LOAD_DISTRIBUTION = insFld(IO, gFld("Load Distribution", ""))	
		insDoc(LOAD_DISTRIBUTION, gLnk("File Location", "/orb/jsp/oracle/io/FileLocation.jsp"))
		insDoc(LOAD_DISTRIBUTION, gLnk("Move Data File", "/orb/jsp/oracle/io/MoveFile.jsp"))
		insDoc(LOAD_DISTRIBUTION, gLnk("Contention?", "/orb/jsp/oracle/io/ReadWrite.jsp?"))

	insDoc(IO, gLnk("Table Scan", "/orb/jsp/oracle/io/TableScan.jsp"))			
	insDoc(IO, gLnk("Data & Index Contention", "/orb/jsp/oracle/io/TableIndex.jsp?"))			

	PARTITION = insFld(IO, gFld("Partition", ""))	
		insDoc(PARTITION, gLnk("Partition", "/orb/jsp/oracle/io/Partition.jsp"))

	FRAGMENTATION = insFld(IO, gFld("Fragmentation", ""))	
		insDoc(FRAGMENTATION, gLnk("Fragmentated?", "/orb/jsp/oracle/space/Fragmentation.jsp"))
		insDoc(FRAGMENTATION, gLnk("Use Proper Size", ""))
		insDoc(FRAGMENTATION, gLnk("Create New Table & Move Data", ""))
		insDoc(FRAGMENTATION, gLnk("Export, Compress, & Import", ""))
		insDoc(FRAGMENTATION, gLnk("Increase Extent Size", ""))

	ROW_CHAIN = insFld(IO, gFld("Row Chain", ""))	

	LOG_CONTENTION = insFld(IO, gFld("Log Contention", ""))	
		insDoc(LOG_CONTENTION, gLnk("Log Info", "/orb/jsp/oracle/io/Log.jsp"))
		insDoc(LOG_CONTENTION, gLnk("Last 100 Logs", "/orb/jsp/oracle/io/LogHistory.jsp"))
		insDoc(LOG_CONTENTION, gLnk("Some commands", "/orb/jsp/oracle/io/LogCommand.jsp"))

	SORTING = insFld(IO, gFld("Sorting", ""))	
		insDoc(SORTING, gLnk("Parameters", "/orb/jsp/oracle/io/SortParameter.jsp"))
		insDoc(SORTING, gLnk("When", "/orb/jsp/oracle/io/WhenToSort.jsp"))
		insDoc(SORTING, gLnk("Where", "/orb/jsp/oracle/io/WhereToSort.jsp"))
		insDoc(SORTING, gLnk("What TS", "/orb/jsp/oracle/io/TempTS.jsp"))

	RBS = insFld(IO, gFld("RBS", ""))

	CONTROL_FILE = insFld(IO, gFld("Control File", ""))	

SPACE = insFld(fT, gFld("Space Management", ""))
	insDoc(SPACE, gLnk("Object Counts/User", "/orb/jsp/oracle/space/ObjCount.jsp"))
	insDoc(SPACE, gLnk("Space Usage/User", "/orb/jsp/oracle/space/UserSpace.jsp"))
	insDoc(SPACE, gLnk("TS Usage & Free Space", "/orb/jsp/oracle/space/TSSpace.jsp"))
	insDoc(SPACE, gLnk("Obj Size Summary By Type", "/orb/jsp/oracle/space/ObjSizeSumm.jsp"))
	insDoc(SPACE, gLnk("Big Objs", "/orb/jsp/oracle/space/ObjSize.jsp"))
	insDoc(SPACE, gLnk("Fragmented Objs", "/orb/jsp/oracle/space/Fragmentation.jsp"))
	insDoc(SPACE, gLnk("Blook Needed/Table", "/orb/jsp/oracle/space/BlockCountFrame.jsp"))
	insDoc(SPACE, gLnk("Extent Summary/User", "/orb/jsp/oracle/space/ExtentSummaryFrame.jsp"))
	FREE_SPACE = insFld(SPACE, gFld("Free Space", ""))
		insDoc(FREE_SPACE, gLnk("Inside TS", "/orb/jsp/oracle/space/TSFreeSpace.jsp"))
		insDoc(FREE_SPACE, gLnk("Inside Data File", "/orb/jsp/oracle/space/FreeSpace.jsp"))
		insDoc(FREE_SPACE, gLnk("Coalesce", "/orb/jsp/oracle/space/CoalesceFrame.jsp"))
	insDoc(SPACE, gLnk("TS, Data File, & Free Space", "/orb/jsp/oracle/space/TSFileFreeSpace.jsp"))
	insDoc(SPACE, gLnk("Data File Map", "/orb/jsp/oracle/space/FileMap.jsp"))
	insDoc(SPACE, gLnk("Tables & Indexes Per TS", "/orb/jsp/oracle/space/ObjPerTS.jsp"))
	insDoc(SPACE, gLnk("Segment Extent By Owner Segment Name", "/orb/jsp/oracle/space/SegExtSummaryFrame.jsp"))
	insDoc(SPACE, gLnk("Segment Extent By Owner", "/orb/jsp/oracle/space/SegExtSummaryFrame1.jsp"))

CONTENTION = insFld(fT, gFld("Contention Management", ""))
	LATCHES = insFld(CONTENTION, gFld("Latches", ""))
		insDoc(LATCHES, gLnk("Overview", "/orb/jsp/oracle/lock/LatchOverview.jsp"))
		insDoc(LATCHES, gLnk("Hit Ratio", "/orb/jsp/oracle/lock/LatchHitRatio.jsp"))
		insDoc(LATCHES, gLnk("Process Hoding", "/orb/jsp/oracle/lock/LatchProcessHolding.jsp"))
		insDoc(LATCHES, gLnk("Process Waiting", "/orb/jsp/oracle/lock/LatchProcessWaiting.jsp"))
		RBS = insFld(LATCHES, gFld("RBS", ""))
			insDoc(RBS, gLnk("Overview", "/orb/jsp/oracle/lock/RollbackSegsOverview.jsp"))
			insDoc(RBS, gLnk("RBS", "/orb/jsp/oracle/lock/RollbackSegs.jsp"))
			insDoc(RBS, gLnk("Shrink", "/orb/jsp/oracle/lock/RollbackShrink.jsp"))
			insDoc(RBS, gLnk("Discrete", "/orb/jsp/oracle/lock/DiscreteTransaction.jsp"))
			insDoc(RBS, gLnk("Locks", "/orb/jsp/oracle/lock/RollbackLock.jsp"))
		insDoc(LATCHES, gLnk("Redo Log Buffer", "/orb/jsp/oracle/lock/RedoLogBuffer.jsp"))
		insDoc(LATCHES, gLnk("LRU", "/orb/jsp/oracle/lock/LRU.jsp"))
		insDoc(LATCHES, gLnk("Free List", "/orb/jsp/oracle/lock/FreeList.jsp"))
		insDoc(LATCHES, gLnk("Spin Count", "/orb/jsp/oracle/lock/LatchSpinCount.jsp"))
		insDoc(LATCHES, gLnk("Who", "/orb/jsp/oracle/user/Session.jsp"))

	USER_LOCK = insFld(CONTENTION, gFld("User Lock", ""))
		insDoc(USER_LOCK, gLnk("Overview", "/orb/jsp/oracle/lock/LockOverview.jsp"))
		insDoc(USER_LOCK, gLnk("Who Locks Who", "/orb/jsp/oracle/lock/WhoLocksWho.jsp"))
		insDoc(USER_LOCK, gLnk("Whos is doing What", "/orb/jsp/oracle/lock/WhoDoesWhat.jsp"))
		insDoc(USER_LOCK, gLnk("DDL", "/orb/jsp/oracle/lock/DDLLock.jsp"))
		insDoc(USER_LOCK, gLnk("DML", "/orb/jsp/oracle/lock/DMLLock.jsp"))

	ENQUEUE = insFld(CONTENTION, gFld("Enqueue", ""))
		insDoc(ENQUEUE, gLnk("Lock", "/orb/jsp/oracle/lock/Enqueue.jsp"))

OBJECT = insFld(fT, gFld("Object Management", ""))
	insDoc(OBJECT, gLnk("Object Management", "/orb/jsp/oracle/schema/SchemaFrame.jsp"))
	insDoc(OBJECT, gLnk("Analyze Object", "/orb/jsp/oracle/schema/AnalyzeFrame.jsp"))